### ISSUE TITLE
NVIDIA driver EGL layer unavailable for rendering

### ISSUE THREAD

**Issue by razoumov** [ComputeCanada/software-stack#63] opened 2021-03-23 19:54 UTC
On Cedar, Graham, Béluga, when rendering with OpenGL on GPUs, all GPUs eventually get into a "locked state" and produce an error

( 2.533s) [main thread ] vtkEGLRenderWindow.cxx:381 ERR| vtkEGLRenderWindow (0x6d73360): Only EGL 1.4 and greater allows OpenGL as client API. See eglBindAPI for more information.

We have EGL 1.4 or later provided by the recent NVIDIA driver. The node reboot always fixes this problem. We had this problem since the initial deployment of Cedar and Graham. None of the other HPC centres seem to have this problem, so we suspect it is caused by some incompatibility between the CC software stack and the NVIDIA drivers.

On the public forums this problem is always solved by updating the NVIDIA drivers. This is not the issue in our case.

**Comment by bartoldeman** [comment] 2021-03-23 20:26
@razoumov Is there any difference here between StdEnv/2016.4 and StdEnv/2020 here?

**Comment by razoumov** [comment] 2021-03-23 21:21
No, not as far as I can tell. The same problem shows up in both. I just tested on Beluga with StdEnv/2020.

**Comment by razoumov** [comment] 2021-03-23 21:28
To recreate the problem, on Beluga I created `/home/razoumov/testEGL` -- modify and then run `gpu.sh`.

**Comment by jfaurelacroix** [comment] 2021-04-19 18:45
On Beluga, I seem to run into the issue right away when the local client connects to the server.

**Comment by bartoldeman** [comment] 2021-04-20 17:55
a strace reveals it's using the mesa libEGL
```
[pid 32674] openat(AT_FDCWD, "/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib64/libEGL_mesa.so.0", O_RDONLY|O_CLOEXEC) = 23
```
now just need to figure out why

**Comment by bartoldeman** [comment] 2021-04-20 19:11
@razoumov what seems to happen here is that it tries the NVidia EGL library but fails because of permission errors; this is even visible with the basic `eglinfo` test program:
```
stat("/dev/nvidia0", {st_mode=S_IFCHR|0666, st_rdev=makedev(0xc3, 0), ...}) = 0
openat(AT_FDCWD, "/dev/nvidia0", O_RDWR) = -1 EPERM (Operation not permitted)
ioctl(3, _IOC(_IOC_READ|_IOC_WRITE, 0x46, 0x2a, 0x20), 0x7fff048f6cb0) = 0
write(1, "eglinfo: eglInitialize failed\n", 30) = 30
write(1, "\n", 1)                       = 1
```
it then falls back to the Mesa EGL library which uses CPU only rendering.

If I force the nvidia library using
`export __EGL_VENDOR_LIBRARY_FILENAMES=/usr/share/glvnd/egl_vendor.d/10_nvidia.json`
your example script gives a segmentation fault, and eglinfo simply complains:

```
EGL client extensions string:
    EGL_EXT_platform_base EGL_EXT_device_base
    EGL_KHR_client_get_all_proc_addresses EGL_EXT_client_extensions
    EGL_KHR_debug EGL_KHR_platform_x11 EGL_EXT_platform_x11
    EGL_EXT_platform_device

X11 platform:
eglinfo: eglInitialize failed

Device platform:
eglinfo: eglInitialize failed
```

I'm not sure why access to `/dev/nvidia0` fails; the device permissions (`crw-rw-rw-`) are ok, must be something on the driver side that denies access, need to dig some more what that is.

**Comment by mboisson** [comment] 2021-04-20 19:14
@bartoldeman, can you confirm that `/dev/nvidia0` is the GPU assigned to the job ? You can compare the GPU UUID returned by `nvidia-smi` inside the job with the GPUs UUID on the same node outside the job. It may be that for some reason, it attempts to use `/dev/nvidia0`, but is supposed to be using another one, and the device cgroups are blocking it.

**Comment by mboisson** [comment] 2021-04-20 19:15
Alternatively, you can test whether the same issue happens if you request all of the GPUs of the node for a given job.

**Comment by bartoldeman** [comment] 2021-04-20 20:11
Indeed the combination of `--gres=gpu:4` and `export __EGL_VENDOR_LIBRARY_FILENAMES=/usr/share/glvnd/egl_vendor.d/10_nvidia.json` makes `eglinfo` work properly (not sure about paraview yet). I'll try more tomorrow.

**Comment by jfaurelacroix** [comment] 2021-04-20 20:44
Ok yes, I can confirm that Paraview now works for me using this workaround.

**Comment by mboisson** [comment] 2021-04-20 20:48
I suspect that it might work whenever `/dev/nvidia0` is the GPU which has actually been assigned to the job. It must somehow hardcode that device somewhere. Maybe this is an NVidia bug ?

**Comment by razoumov** [comment] 2021-04-20 20:56
Testing on Béluga, if I ask for all GPUs on a node:

#SBATCH --gres=gpu:4
#SBATCH --nodes=1-1

I get a segmentation fault with:

libEGL warning: failed to open /dev/dri/renderD131: Permission denied
libEGL warning: Not allowed to force software rendering when API explicitly selects a hardware device.
libEGL warning: failed to open /dev/dri/renderD131: Permission denied

Setting `export LD_LIBRARY_PATH=/lib64/nvidia:$LD_LIBRARY_PATH`, it works and renders on one (I suspect) of the GPUs.

@jfaurelacroix Which workaround worked for you?

**Comment by jfaurelacroix** [comment] 2021-04-20 21:02
I used salloc with with gpu:4 and the export before running pvserver.
It doesn't work with gpu:1

**Comment by razoumov** [comment] 2021-04-20 21:04
Testing right now, for me gpu:1 works occasionally, so Maxime might be right (that it works when /dev/nvidia0 is assigned to the job).

**Comment by jfaurelacroix** [comment] 2021-04-20 21:08
Yeah it smells like something's hardcoded somewhere

**Comment by bartoldeman** [comment] 2021-04-21 14:45
https://hpc.nih.gov/apps/paraview.html suggests that `--egl-device-index=$CUDA_VISIBLE_DEVICES` should do the trick. I'll do some more tests to see if which env vars we really need:
1. LD_LIBRARY_PATH (ideally we should not need this)
2. __EGL_VENDOR_LIBRARY_FILENAMES

**Comment by mboisson** [comment] 2021-04-21 15:04
Note that `$CUDA_VISIBLE_DEVICES` is always `0` when using cgroups (and requesting for only 1 GPU). 

`$CUDA_VISIBLE_DEVICES` can also set to be a list of device UUID. 
https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#env-vars

but I doubt that if they want a `device-index`, they accept UUIDs.

**Comment by mboisson** [comment] 2021-04-21 15:06
This is relevant: https://forums.developer.nvidia.com/t/egl-stopped-working-in-slurm-cgroups-environment-with-driver-upgrade/170011

**Comment by bartoldeman** [comment] 2021-04-21 16:39
this works for me:
```
#!/bin/bash
#SBATCH --gres=gpu:1
#SBATCH --mem=3600M
#SBATCH --time=00:10:00
#SBATCH --account=cc-debug
unset DISPLAY
module load StdEnv/2020 gcc/9.3.0 paraview-offscreen-gpu/5.8.0
export __EGL_VENDOR_LIBRARY_FILENAMES=/usr/share/glvnd/egl_vendor.d/10_nvidia.json
pvbatch --egl-device-index=$SLURM_STEP_GPUS wavelet.py
```
it complains with
```
(   1.263s) [main thread     ] vtkEGLRenderWindow.cxx:381    ERR| vtkEGLRenderWindow (0x4889cf0): Only EGL 1.4 and greater allows OpenGL as client API. See eglBindAPI for more information.
(   1.263s) [main thread     ]vtkOpenGLRenderWindow.c:565    ERR| vtkEGLRenderWindow (0x4889cf0): GLEW could not be initialized: Missing GL version
```
if you get GPU 1,2, or 3 allocated but it works anyway.

I'll adjust the CC software stack gentoo layer (libglvnd library) so you will no longer need the `export`.

**Comment by razoumov** [comment] 2021-04-21 17:32
@mboisson The bug is present on all 3 clusters (Béluga, Graham and Cedar): I tested yesterday on all three.

**Comment by razoumov** [comment] 2021-04-21 17:39
@bartoldeman Hm-m, your exact script is not working for me on Beluga (getting a segfault, no image).

**Comment by bartoldeman** [comment] 2021-04-21 17:45
I just submitted again @razoumov , no problem, we'll need to check .bashrc.

**Comment by razoumov** [comment] 2021-04-21 17:49
$SLURM_STEP_GPUS is empty for me, with --gres=gpu:1 on Beluga.

**Comment by bartoldeman** [comment] 2021-04-21 17:49
@razoumov it was salloc vs sbatch that caught me: we need to use `$SLURM_JOB_GPUS` instead:
```
#!/bin/bash
#SBATCH --gres=gpu:1
#SBATCH --mem=3600M
#SBATCH --time=00:10:00
#SBATCH --account=cc-debug
unset DISPLAY
module load StdEnv/2020 gcc/9.3.0 paraview-offscreen-gpu/5.8.0
echo $SLURM_JOB_GPUS
export __EGL_VENDOR_LIBRARY_FILENAMES=/usr/share/glvnd/egl_vendor.d/10_nvidia.json
pvbatch --egl-device-index=$SLURM_JOB_GPUS wavelet.py
```

**Comment by razoumov** [comment] 2021-04-21 17:53
Confirming: it worked!

**Comment by razoumov** [comment] 2021-04-21 21:35
I am still running into the same error on Graham with the new script:

```
#!/bin/bash
#SBATCH --gres=gpu:1
#SBATCH --mem=3600M
#SBATCH --time=00:10:00
#SBATCH --account=def-razoumov-ac
unset DISPLAY
module load gcc/9.3.0 paraview-offscreen-gpu/5.8.0
echo We are running on $(nvidia-smi -L)
echo In reality assigned GPU$SLURM_JOB_GPUS
export __EGL_VENDOR_LIBRARY_FILENAMES=/usr/share/glvnd/egl_vendor.d/10_nvidia.json
pvbatch --egl-device-index=$SLURM_JOB_GPUS wavelet.py
```

We are running on GPU 0: Tesla P100-PCIE-12GB (UUID: GPU-11000e73-fd02-8f72-8771-923ad1c3b36f)
In reality assigned GPU1
(   3.852s) [main thread     ] vtkEGLRenderWindow.cxx:295   WARN| vtkEGLRenderWindow (0x556d120): EGL device index: 0 is greater than the number of su
pported deviced in the system: 0. Using device 0 ...
(   3.852s) [main thread     ] vtkEGLRenderWindow.cxx:381    ERR| vtkEGLRenderWindow (0x556d120): Only EGL 1.4 and greater allows OpenGL as client API
. See eglBindAPI for more information.
(   3.852s) [main thread     ]vtkOpenGLRenderWindow.c:565    ERR| vtkEGLRenderWindow (0x556d120): GLEW could not be initialized: Missing GL version

**Comment by bartoldeman** [comment] 2021-04-22 16:58
confirmed, it works on Cedar and Béluga, but not on Graham.
The Graham error to look out for is this:
```
( 3.852s) [main thread ] vtkEGLRenderWindow.cxx:295 WARN| vtkEGLRenderWindow (0x556d120): EGL device index: 0 is greater than the number of supported deviced in the system: 0. Using device 0 ...
```
it even has a typo!

However on Graham one can you `--gres=gpu:2` and then it works ok (with plain `pvbatch wavelet.py`) though you're wasting one GPU.

**Comment by mboisson** [comment] 2021-04-22 17:40
So... it doesn't work on the most recent GPU driver ?....

**Comment by bartoldeman** [comment] 2021-04-22 18:04
Beluga did better than this in the reservation (with an even newer driver)

**Comment by bartoldeman** [comment] 2021-04-22 18:08
Béluga: 460.73.01 -> works if you specify GPU explicitly, or if you reserve all GPUs
Graham: 460.32.03 -> works only if you reserve all GPUs
Béluga: 450.51.06 -> works if you specify GPU explicitly, or if you reserve all GPUs
Cedar: 455.45.01 -> works if you specify GPU explicitly, or if you reserve all GPUs

**Comment by mboisson** [comment] 2021-07-29 13:41
I just tested with Cedar's newly updated drivers (470.57.02) and it seems to resolve the problem. 
```
#!/bin/bash

#SBATCH --time=01:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --gres=gpu:1
#SBATCH --mem-per-cpu=4000M
#SBATCH --account=def-mboisson
unset DISPLAY
module load gcc/9.3.0 paraview-offscreen-gpu/5.8.0
echo We are running on $(nvidia-smi -L)
echo In reality assigned GPU$SLURM_JOB_GPUS
echo "Running pvbatch without parameters first"
pvbatch wavelet.py
echo "Now running with modified config"
export __EGL_VENDOR_LIBRARY_FILENAMES=/usr/share/glvnd/egl_vendor.d/10_nvidia.json
pvbatch --egl-device-index=$SLURM_JOB_GPUS wavelet.py
``` 

results in : 
```
$ cat slurm-8913794.out

Lmod a automatiquement remplacé "intel/2020.1.217" par "gcc/9.3.0"


Dû à un changement dans la variable MODULEPATH, les modules suivants ont été rechargés :
  1) openmpi/4.0.3

We are running on GPU 0: Tesla P100-PCIE-12GB (UUID: GPU-97bc3391-472d-f249-c96d-e2eddaa6b3ac)
In reality assigned GPU1
Running pvbatch without parameters first
Now running with modified config
(   1.723s) [main thread     ] vtkEGLRenderWindow.cxx:295   WARN| vtkEGLRenderWindow (0x538c090): EGL device index: 1 is greater than the number of supported deviced in the system: 1. Using device 0 ...
``` 

So, the script with the workaround now actually produces a warning (but falls back on the correct GPU), and running pvbatch without the workaround works just fine.

**Comment by mboisson** [comment] 2021-08-10 18:20
As of August 10th, 2021, Béluga and Cedar have upgrade. Just missing Graham.

**Comment by mboisson** [comment] 2022-04-04 15:07
This is now fixed by new GPU drivers on Graham.

**Closed by mboisson** 2022-04-04 15:07 UTC
